### PR TITLE
Add Regular Expression Support

### PR DESCRIPTION
**Pull request by ed0906**
Currently the module only matches on strings, I have added functionality to expand on this and match on Regular Expressions or arrays of Regular expressions.

### CODE REVIEW

**Comment by callumacrae** [comment]
Awesome! Can you add a test for mixed arrays?

**Comment by ed0906** [comment]
@callumacrae Of course :D

**Comment by ed0906** [comment]
There should be a mixed array test now

**Comment by callumacrae** [comment]
Nice. Thanks!

**Comment by callumacrae** [comment]
Published as 1.1.0.

**Pull request merged**
