### PR TITLE
Replace gulp-util.File with vinyl, gulp-util.PluginError with plugin-error

### PR DESCRIPTION
**Pull request by petasittek**
gulp-util is deprecated:
- https://www.npmjs.com/package/gulp-util
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### CODE REVIEW

**Comment by petasittek** [comment]
@callumacrae: Any chance of this being merged anytime soon?

**Comment by callumacrae** [comment]
Sorry for the delay!

I don't maintain this project anymore, but if you give me your npm username I'd be happy to add you as a maintainer :)

**Comment by callumacrae** [comment]
also, looks good to me - thanks for your work on this

**Comment by petasittek** [comment]
https://www.npmjs.com/~petasittek

**Comment by petasittek** [comment]
Cool, let's merge! ;)

**Comment by callumacrae** [comment]
have added you to both this repo and npm :)

**Pull request merged**
